"""The idealized-heart records: three variants on cardiacFOAM's own idealized
biventricular mesh, tracked natively (design doc's coordinator follow-up,
step S4, 2026-09-28).

Unlike ``humanSlab`` (``anatomy.py``), this mesh and its coordinate fields
are committed natively (``cases/idealized*``, Git LFS) -- no
``--input`` is needed. It uses the ``cobiveco`` convention, whose fields are
named ``tm``/``tv``/``apicobasal`` (never ``uvc_*``), confirmed against the
mesh's own ``ENDO_LV``/``ENDO_RV``/``EPI``/``BASE`` boundary patches (see the
native commit message for the full evidence): ``tm`` 1=endocardium/
0=epicardium, ``tv`` 0=LV/1=RV, ``apicobasal`` 0=apex/1=base. Its own
``coordinatesConventionDict`` states this mapping; the ``consumes`` paths
below name the literal field files it actually has, which is why this module
cannot reuse ``anatomy.py``'s ``UVC``/step constants (bivCase's own
``uvc_*`` names) -- a step's ``consumes`` is a real case-relative path, not
a convention-independent alias.
"""

from __future__ import annotations

from omnidriver.core.tutorial_records import RecordInput, TutorialRecord

from .anatomy import CONV, MESH, TREE_OUT, step

#: The idealized mesh's own coordinate fields (cobiveco naming).
COBIVECO = ("0/tm", "0/tv", "0/apicobasal")

#: generatePurkinjeTree's own outputs under `coordinateSystem cobiveco`:
#: unlike `anatomy.TREE_OUT` (bivCase's own `uvc`), no `RVSeptalEndoFaces`
#: set is built at all -- confirmed running this for real (its README already
#: says so: "no RVSeptalEndoFaces recovery is needed or constructed", since
#: cobiveco solves transmural/intraventricular membership per chamber, so
#: the septum already reads endocardial from both sides).
COBIVECO_TREE_OUT = tuple(path for path in TREE_OUT if "RVSeptalEndoFaces" not in path)

#: This mesh's own polyMesh, in full: `anatomy.MESH` (shared with
#: `humanSlab`'s supplied bundle) lists only the five files that bundle
#: actually has; this committed mesh also carries `cellZones`/`faceZones`/
#: `pointZones` (standard, if unused, mesh-topology files) -- found by C11
#: (restaging dropped all three, since only the five in `MESH` were ever
#: copied by the input overlay).
IDEALIZED_MESH = MESH + tuple(
    f"constant/polyMesh/{name}" for name in ("cellZones", "faceZones", "pointZones")
)


def _mesh_input(native_case_relpath: str) -> RecordInput:
    """``constant/polyMesh`` as a *native-location* input (design §3's own
    idea for cardiacFOAM's idealized-heart mesh, applied here): every
    OpenFOAM-based record's staging excludes ``polyMesh`` from the plain
    native-case copy unconditionally
    (``openfoam.case_runtime_conventions``'s own ``generated_directory_names``
    -- a factory tutorial's own mesh is always either generated by a
    ``blockMesh``/``gmshToFoam`` step or supplied). This mesh is neither: it
    is committed, authored data with no generating step in this record at
    all -- found running ``idealizedHeart`` for real (the mesh was silently
    absent from the staged case, and ``setCardiacConductivity`` failed
    "Cannot find file 'points'"). Declaring it as an input whose
    ``native_relpath`` is the record's own case folder resolves it
    automatically (the "no supplied input" the record needs, since a
    ``RecordInput`` with a native location never asks for ``--input``) while
    also opting it back into staging via the overlay mechanism, reading the
    committed bytes directly rather than through the excluded native-copy
    step.
    """
    return RecordInput(
        name="mesh",
        native_relpath=native_case_relpath,
        files=tuple((path, path) for path in IDEALIZED_MESH),
    )

CONDUCTIVITY = step(
    "conductivity", "setCardiacConductivity",
    # *IDEALIZED_MESH (all eight polyMesh files, not `anatomy.MESH`'s five):
    # every destination a record's input declares must be tied to some
    # step's `consumes` (design §2.1), and this input's own `files` list
    # covers the full committed mesh, `cellZones`/`faceZones`/`pointZones`
    # included -- they are read the same way the other five are, as part of
    # one `fvMesh` construction (`createMesh.H`), never individually by name.
    consumes=(*IDEALIZED_MESH, "0/fiber", "0/sheet"),
    produces=("0/Conductivity",),
)

ANATOMY_STEP = step(
    "anatomy", "setCardiacAnatomy",
    consumes=(CONV, "0/apicobasal", "0/tv"),
    produces=("0/aha_angle", "0/phiRV", "0/groove_interface", "0/AHA_Segment"),
)

MORPHOMETRY = step(
    "purkinje_morphometry", "setPurkinjeMorphometry",
    consumes=(CONV, "0/apicobasal", "0/tv"),
    produces=(
        "0/PurkinjeLongitudinalRegion", "0/PurkinjeCircumferentialRegion",
        "0/PurkinjeTerminalWeightSubendocardial", "0/PurkinjeTerminalWeightIntramural",
    ),
)

#: idealizedHeart: mirrors humanSlab's own workflow (conductivity, anatomy,
#: slab, morphometry), on the idealized mesh instead of the supplied bivCase
#: bundle.
IDEALIZED_HEART = TutorialRecord(
    name="idealizedHeart",
    native_case_relpath="cases/idealizedHeart",
    inputs=(_mesh_input("cases/idealizedHeart"),),
    workflow_steps=(
        CONDUCTIVITY,
        ANATOMY_STEP,
        step(
            "purkinje_slab", "setPurkinjeSlab",
            consumes=(CONV, "0/tm"),
            produces=("0/PurkinjeLayer", "0/Conductivity"),
        ),
        MORPHOMETRY,
    ),
)

#: idealizedHeartEndocardial: mirrors humanEndocardial's own workflow
#: (conductivity, anatomy, generatePurkinjeTree -- LV/RV allLeaves+
#: endocardial, per its own committed system/generatePurkinjeTreeDict).
#: 1DgraphToFoam is left out (D4, unchanged from humanEndocardial).
IDEALIZED_HEART_ENDOCARDIAL = TutorialRecord(
    name="idealizedHeartEndocardial",
    native_case_relpath="cases/idealizedHeartEndocardial",
    inputs=(_mesh_input("cases/idealizedHeartEndocardial"),),
    workflow_steps=(
        CONDUCTIVITY,
        ANATOMY_STEP,
        step(
            "purkinje_tree", "generatePurkinjeTree",
            consumes=(CONV, *COBIVECO),
            produces=COBIVECO_TREE_OUT,
        ),
    ),
)

#: idealizedHeartPigTransmural: mirrors pigMorphometricTransmural's own
#: workflow (conductivity, anatomy, morphometry, generatePurkinjeTree -- LV
#: weightedField+transmural, RV allLeaves+transmural).
IDEALIZED_HEART_PIG_TRANSMURAL = TutorialRecord(
    name="idealizedHeartPigTransmural",
    native_case_relpath="cases/idealizedHeartPigTransmural",
    inputs=(_mesh_input("cases/idealizedHeartPigTransmural"),),
    workflow_steps=(
        CONDUCTIVITY,
        ANATOMY_STEP,
        MORPHOMETRY,
        # `0/PurkinjeTerminalWeight{Subendocardial,Intramural}` are not
        # re-declared as consumed here: they are MORPHOMETRY's own
        # `produces`, an intermediate rather than an authored input -- the
        # same C8 finding as humanSlab's own `0/Conductivity` (S3, S7).
        step(
            "purkinje_tree", "generatePurkinjeTree",
            consumes=(CONV, *COBIVECO),
            produces=COBIVECO_TREE_OUT,
        ),
    ),
)
