"""Bind persisted checkpoints to the workflow and observed input evidence.

The snapshot describes a checkpoint, including files generated by preceding
steps. It is not a build attestation or a proof of all runtime dependencies.
Legacy state without evidence is readable for inspection but cannot resume.
"""
from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import TYPE_CHECKING, Mapping

from .provenance import ProvenanceSnapshot, compare, snapshot_from_components
from .provenance_inputs import enumerate_case_inputs
from .reconciler import declared_instance_names, reconcile_artifacts
from .workflow_state import WorkflowRunState, workflow_digest
from .models import DataArtifact

if TYPE_CHECKING:
    from ..plugin_interface import DriverContext


# ``load_openfoam_environment`` uses this path only to communicate a sourced
# environment from a helper shell back to Python.  A fresh temporary filename
# is created every load, and it is never inherited by the workflow command as
# a solver setting.  Hashing it made an unchanged public CLI invocation
# spuriously non-resumable.
_VOLATILE_ENVIRONMENT_KEYS = frozenset({"_DRIVER_ENV_FILE"})


def _environment_identity(environment: Mapping[str, str]) -> dict[str, str]:
    """Return execution-relevant environment values for checkpoint identity."""
    return {
        key: value for key, value in environment.items()
        if key not in _VOLATILE_ENVIRONMENT_KEYS
    }


def checkpoint_snapshot(case_root: Path, workflow_dag: dict, driver_context: DriverContext,
                        env: Mapping[str, str] | None) -> dict:
    """Build the identity a resumed run's evidence is compared against.

    ``plugin_identity`` here is the FULL ``driver_context.identity.to_json()``
    (every ``ProviderIdentity``, including its ``source``) plus an
    ``environment_digest`` over the execution environment -- not the
    ``provider_identity.STACK_IDENTITY_COMPARISON_KEYS`` subset that
    ``stack_identity_mismatch`` uses for plan/run/compare stack binding
    (added 2026-09-26, final review M4). That is intentional: resuming a
    checkpoint replays a specific prior attempt, so an import path or
    environment change resume would otherwise miss is exactly what must
    force a fresh run, even though the same change is not a "different
    stack" for binding purposes. See ``runtime.provenance.compare`` for
    where the full-identity comparison is applied.
    """
    environment = dict(os.environ if env is None else env)
    # Store only the digest, not potentially secret environment values.
    stable_environment = _environment_identity(environment)
    env_digest = hashlib.sha256(json.dumps(stable_environment, sort_keys=True).encode()).hexdigest()
    identity = {**driver_context.identity.to_json(), "environment_digest": env_digest}
    snapshot = snapshot_from_components(
        enumerate_case_inputs(case_root, workflow_dag=workflow_dag,
                              driver_context=driver_context, env=environment),
        workflow_digest=workflow_digest(workflow_dag), plugin_identity=identity,
    )
    return json.loads(snapshot.to_json())


def validate_resume(state: WorkflowRunState, workflow_dag: dict, *, case_root: Path,
                    driver_context: DriverContext | None, env: Mapping[str, str] | None,
                    expected_artifacts: tuple[DataArtifact, ...] = ()) -> None:
    """Refuse reuse unless checkpoint identity and completed outputs still hold.

    A terminal state is an assertion about a particular attempt, not a cache
    key.  Input provenance establishes that the saved attempt describes the
    current request; required artifacts establish that its completion claim
    remains observable.  Artifact freshness is enforced at execution time,
    while this resume gate intentionally checks only continued presence.
    """
    if state.workflow_digest != workflow_digest(workflow_dag):
        raise ValueError("Saved workflow identity is missing or changed; create a fresh run instead of reusing this state")
    expected = {str(step["id"]): step for step in workflow_dag["steps"]}
    actual = {step.step_id: step for step in state.steps}
    if len(actual) != len(state.steps) or set(actual) != set(expected):
        raise ValueError("Saved workflow steps do not match the current DAG")
    completed = {step.step_id for step in state.steps if step.status == "completed"}
    if set(state.completed_steps) != completed or len(state.completed_steps) != len(completed):
        raise ValueError("Saved completed-step list is inconsistent")
    if state.status == "completed" and (completed != set(expected) or state.current_step_id is not None):
        raise ValueError("Saved workflow claims completion without completing every step")
    if state.current_step_id is not None and state.current_step_id not in actual:
        raise ValueError("Saved current step is not in the DAG")
    for name, step in actual.items():
        spec = expected[name]
        if (step.command, step.args, step.cwd) != (
            str(spec["command"]), tuple(str(arg) for arg in spec.get("args", ())), str(spec.get("cwd", "."))
        ):
            raise ValueError(f"Saved command for step {name!r} differs from the current DAG")
        if step.status == "completed" and not set(spec.get("depends_on", ())).issubset(completed):
            raise ValueError(f"Saved completed step {name!r} has incomplete dependencies")
    # A zero-budget checkpoint has not consumed inputs and may start normally.
    if all(step.attempt == 0 and step.status == "pending" for step in state.steps):
        return
    if driver_context is None or state.resume_snapshot is None:
        raise ValueError("Saved workflow has no input evidence; create a fresh run")
    before = ProvenanceSnapshot.from_json(json.dumps(state.resume_snapshot))
    after = ProvenanceSnapshot.from_json(json.dumps(checkpoint_snapshot(case_root, workflow_dag, driver_context, env)))
    if not before.is_complete or not after.is_complete:
        raise ValueError("Saved workflow cannot resume with incomplete or metadata-only input evidence")
    differences = compare(before, after)
    if before.schema_version != after.schema_version or differences:
        paths = ", ".join(diff.path for diff in differences)
        raise ValueError(f"Saved workflow input evidence changed ({paths or 'fingerprint policy'}); create a fresh run")
    if state.status == "completed":
        report = reconcile_artifacts(
            case_root,
            expected_artifacts,
            instance_names=declared_instance_names(
                case_root, driver_context=driver_context,
            ),
        )
        missing = [
            entry["artifact_id"]
            for entry in report.artifacts
            if not entry["optional"] and entry["status"] != "matched"
        ]
        if missing:
            raise ValueError(
                "Saved workflow required outputs are missing "
                f"({', '.join(missing)}); create a fresh run instead of reusing this state"
            )
